import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Login from './login'
import { useState } from 'react'
import useLocalStorage from '@/components/useLocalStorage'
import UserOverview from './userOvierwiew'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [loginId, setLoginId] = useState(false)
  const [allLogins, setAllLogins] = useLocalStorage("household app user data", [])
  const [allHouseholds, setAllHouseholds] = useLocalStorage("household data", [])

  return (
    <>
      <Head>
        <title>CashMoney - equal share</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        {loginId === false ? 
        <Login setLoginId={setLoginId} allLogins={allLogins} setAllLogins={setAllLogins}/> : 
        <div>        
          <UserOverview loginId={loginId} allHouseholds={allHouseholds} setAllHouseholds={setAllHouseholds}/>
          <button onClick={()=>setLoginId(false)}>Log out</button>
        </div>}
      </main>
    </>
  )
}